name: "bc-notification"
on:
  issues:
    types: [edited, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'breaking-change'
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: timheuer/issue-notifier@e49f1d2faf914fe5c7c028162adff3050234c70b
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API }}
        with:
          fromMailAddress: "${{ secrets.BC_NOTIFY }}"
          toMailAddress: "${{ secrets.BC_NOTIFY }}"
          subject: "BC:"
          subjectPrefix: "BC:"
          labelsToMonitor: "breaking-change"
